import{useEffect,useMemo,useRef,useState}from'react';import{CSV_HEADERS,applyRepagination,buildRepagination,detectIssues,filterArchives,importCsv,makeBackup,parseBackup,repageFingerprint,sampleArchives}from'./data';import type{Filters,RepagePreview}from'./data';import type{Archive,BorrowRecord,InventorySession,Resolutions}from'./types';import{INVENTORY_KEY,createSession,parseSessions}from'./inventory';import{BORROW_KEY,borrowArchive,isBorrowed,parseBorrowRecords,returnBorrow}from'./borrow';import InventoryPanel from'./InventoryPanel';import BorrowPanel from'./BorrowPanel';
const ARCHIVES_KEY='archive-audit:archives',RES_KEY='archive-audit:resolutions';
const empty:Omit<Archive,'id'>={archiveNo:'',title:'',year:new Date().getFullYear(),retention:'',boxNo:'',startPage:1,endPage:1,declaredPages:1,note:''};
const load=<T,>(key:string,fallback:T):T=>{try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}};
const download=(name:string,text:string,type:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
export default function App(){const[archives,setArchives]=useState<Archive[]>(()=>load(ARCHIVES_KEY,[]));const[resolutions,setResolutions]=useState<Resolutions>(()=>load(RES_KEY,{}));const[editing,setEditing]=useState<Archive|null>(null);const[form,setForm]=useState<Omit<Archive,'id'>>(empty);const[notice,setNotice]=useState<{kind:'ok'|'error';text:string}|null>(null);const[filters,setFilters]=useState<Filters>({query:'',year:'',box:'',status:'all'});const[repageOpen,setRepageOpen]=useState(false);const[repageBox,setRepageBox]=useState('');const[repageStart,setRepageStart]=useState('1');const[preview,setPreview]=useState<RepagePreview|null>(null);const csvRef=useRef<HTMLInputElement>(null),jsonRef=useRef<HTMLInputElement>(null);const[sessions,setSessions]=useState<InventorySession[]>(()=>parseSessions(localStorage.getItem(INVENTORY_KEY)));const[borrows,setBorrows]=useState<BorrowRecord[]>(()=>parseBorrowRecords(localStorage.getItem(BORROW_KEY)));const[borrowTarget,setBorrowTarget]=useState<Archive|null>(null);const[borrowError,setBorrowError]=useState<string|null>(null);
 useEffect(()=>localStorage.setItem(ARCHIVES_KEY,JSON.stringify(archives)),[archives]);useEffect(()=>localStorage.setItem(RES_KEY,JSON.stringify(resolutions)),[resolutions]);useEffect(()=>localStorage.setItem(INVENTORY_KEY,JSON.stringify(sessions)),[sessions]);useEffect(()=>localStorage.setItem(BORROW_KEY,JSON.stringify(borrows)),[borrows]);const issues=useMemo(()=>detectIssues(archives),[archives]);const visible=useMemo(()=>filterArchives(archives,issues,resolutions,filters),[archives,issues,resolutions,filters]);const years=[...new Set(archives.map(a=>a.year))].sort((a,b)=>b-a);const boxes=[...new Set(archives.map(a=>a.boxNo))].sort();
 const reset=()=>{setEditing(null);setForm({...empty,year:new Date().getFullYear()})};const setField=(k:keyof typeof form,v:string)=>setForm(p=>({...p,[k]:['year','startPage','endPage','declaredPages'].includes(k)?Number(v):v}));
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!form.archiveNo.trim()||!form.title.trim()||!form.retention.trim()||!form.boxNo.trim()){setNotice({kind:'error',text:'请填写所有必填字段'});return}if([form.year,form.startPage,form.endPage,form.declaredPages].some(n=>!Number.isInteger(n)||n<0)){setNotice({kind:'error',text:'年度和页数须为非负整数'});return}const id=editing?.id??crypto.randomUUID();setArchives(p=>editing?p.map(a=>a.id===id?{id,...form}:a):[...p,{id,...form}]);setResolutions(p=>Object.fromEntries(Object.entries(p).filter(([k])=>!k.startsWith(`${id}:`))));setNotice({kind:'ok',text:editing?'档案已更新并重新检查':'档案已新增'});reset()};
 const edit=(a:Archive)=>{setEditing(a);setForm({archiveNo:a.archiveNo,title:a.title,year:a.year,retention:a.retention,boxNo:a.boxNo,startPage:a.startPage,endPage:a.endPage,declaredPages:a.declaredPages,note:a.note});document.getElementById('editor')?.scrollIntoView?.({behavior:'smooth'})};
 const readFile=(file:File,cb:(s:string)=>void)=>{const r=new FileReader();r.onload=()=>cb(String(r.result));r.readAsText(file)};
 const importCSV=(file?:File)=>file&&readFile(file,text=>{try{const added=importCsv(text,archives);setArchives(p=>[...p,...added]);setNotice({kind:'ok',text:`成功导入 ${added.length} 条档案`})}catch(e){setNotice({kind:'error',text:(e as Error).message})}});
 const importJSON=(file?:File)=>file&&readFile(file,text=>{try{const b=parseBackup(text);setArchives(b.archives);setResolutions(b.resolutions);setNotice({kind:'ok',text:`已恢复 ${b.archives.length} 条档案`})}catch(e){setNotice({kind:'error',text:(e as Error).message})}});
 const clearAll=()=>{if(confirm('确定清空全部档案和核对记录？此操作不可撤销。')){setArchives([]);setResolutions({});setNotice({kind:'ok',text:'数据已清空'})}};
 const latestByBox=useMemo(()=>new Map(sessions.map((s):[string,InventorySession]=>[s.boxNo,s])),[sessions]);
 const startInventory=(box:string)=>{const s=createSession(archives,box);if('error'in s){setNotice({kind:'error',text:s.error});return}setSessions(p=>[...p,s]);setNotice({kind:'ok',text:`盒 ${box} 盘点会话已创建：快照 ${s.items.length} 件，创建时间 ${s.createdAt}`})};
 const saveSession=(next:InventorySession)=>setSessions(p=>p.map(s=>s.id===next.id?next:s));
 // 借阅：从档案清单发起，确认时以当时的档案与记录现状为准；失败只提示原因，不产生任何记录
 const startBorrow=(a:Archive)=>{setBorrowTarget(a);setBorrowError(null);document.getElementById('borrowdesk')?.scrollIntoView?.({behavior:'smooth'})};
 const cancelBorrow=()=>{setBorrowTarget(null);setBorrowError(null)};
 const confirmBorrow=(borrower:string,due:string)=>{if(!borrowTarget)return;const r=borrowArchive(borrows,archives,borrowTarget.id,borrower,due);if('error'in r){setBorrowError(r.error);return}setBorrows(r.records);setBorrowTarget(null);setBorrowError(null);setNotice({kind:'ok',text:`${r.record.archiveNo} 已借出给 ${r.record.borrower}，预计 ${r.record.dueDate} 归还`})};
 const doReturn=(recordId:string)=>{const r=returnBorrow(borrows,recordId);if('error'in r){setNotice({kind:'error',text:r.error});return}setBorrows(r.records);setNotice({kind:'ok',text:`${r.record.archiveNo} 已归还，借阅记录已补写归还时间`})};
 const openRepage=()=>{setRepageOpen(true);setRepageBox(boxes.includes(repageBox)?repageBox:boxes[0]||'');setPreview(null)};
 const closeRepage=()=>{setRepageOpen(false);setPreview(null)};
 const runPreview=(e:React.FormEvent)=>{e.preventDefault();setPreview(buildRepagination(archives,resolutions,repageBox,repageStart))};
 const previewStale=!!preview&&!('error'in preview)&&repageFingerprint(archives,resolutions,preview.box)!==preview.fingerprint;
 const confirmRepage=()=>{if(!preview||'error'in preview||previewStale)return;try{const r=applyRepagination(archives,resolutions,preview);const n=r.archives.filter(a=>a.boxNo===preview.box).length;setArchives(r.archives);setResolutions(r.resolutions);setNotice({kind:'ok',text:`盒 ${preview.box} 共 ${n} 件已连续编页，相关旧处置已清除并重新复核`});closeRepage()}catch(e){setPreview({error:(e as Error).message})}};
 const pending=issues.filter(i=>!resolutions[i.key]);const actual=archives.reduce((n,a)=>n+Math.max(0,a.endPage-a.startPage+1),0);const grouped=boxes.map(box=>({box,items:archives.filter(a=>a.boxNo===box).sort((a,b)=>a.startPage-b.startPage)}));
 return <><header><div><span className="eyebrow">ARCHIVE CONTROL DESK</span><h1>纸质档案装盒<br/><em>页码核对台</em></h1><p>把档案、页码和异常放到同一张工作台上。数据仅保存在当前浏览器。</p></div><div className="stamp">自动复核<br/><strong>{pending.length}</strong><small>项待处理</small></div></header><main>
 {notice&&<div className={`notice ${notice.kind}`} role="alert"><span>{notice.kind==='ok'?'✓':'!'}</span><pre>{notice.text}</pre><button onClick={()=>setNotice(null)}>关闭</button></div>}
 <section className="metrics"><article><small>档案总数</small><strong>{archives.length}</strong><span>件</span></article><article><small>已登记页数</small><strong>{actual}</strong><span>页</span></article><article><small>装盒数量</small><strong>{boxes.length}</strong><span>盒</span></article><article className={pending.length?'warn':''}><small>待核对问题</small><strong>{pending.length}</strong><span>项</span></article></section>
 <section className="panel toolbar"><div><h2>数据工作区</h2><p>导入失败时，现有数据不会被覆盖。</p></div><div className="actions"><button onClick={()=>{setArchives(sampleArchives.map(a=>({...a,id:crypto.randomUUID()})));setResolutions({});setNotice({kind:'ok',text:'示例数据已载入'})}}>载入示例</button><button onClick={()=>download('档案核对备份.json',JSON.stringify(makeBackup(archives,resolutions),null,2),'application/json')}>导出 JSON</button><button onClick={()=>jsonRef.current?.click()}>导入 JSON</button><button onClick={()=>csvRef.current?.click()}>导入 CSV</button><button className="danger" onClick={clearAll}>一键清空</button><input hidden ref={csvRef} type="file" accept=".csv,text/csv" onChange={e=>{importCSV(e.target.files?.[0]);e.target.value=''}}/><input hidden ref={jsonRef} type="file" accept=".json,application/json" onChange={e=>{importJSON(e.target.files?.[0]);e.target.value=''}}/></div><details><summary>CSV 标准表头</summary><code>{CSV_HEADERS.join(',')}</code></details></section>
 <section className="panel" id="editor"><div className="section-head"><div><span className="kicker">01 / REGISTER</span><h2>{editing?'编辑档案':'新增档案'}</h2></div>{editing&&<button onClick={reset}>取消编辑</button>}</div><form onSubmit={save} className="form-grid"><label>档号 *<input value={form.archiveNo} onChange={e=>setField('archiveNo',e.target.value)} required/></label><label className="span2">标题 *<input value={form.title} onChange={e=>setField('title',e.target.value)} required/></label><label>年度 *<input type="number" min="0" value={form.year} onChange={e=>setField('year',e.target.value)} required/></label><label>保管期限 *<input value={form.retention} onChange={e=>setField('retention',e.target.value)} placeholder="如：永久 / 30年" required/></label><label>盒号 *<input value={form.boxNo} onChange={e=>setField('boxNo',e.target.value)} required/></label><label>起始页 *<input type="number" min="0" value={form.startPage} onChange={e=>setField('startPage',e.target.value)} required/></label><label>结束页 *<input type="number" min="0" value={form.endPage} onChange={e=>setField('endPage',e.target.value)} required/></label><label>申报页数 *<input type="number" min="0" value={form.declaredPages} onChange={e=>setField('declaredPages',e.target.value)} required/></label><label className="span2">备注<textarea value={form.note} onChange={e=>setField('note',e.target.value)} rows={2}/></label><button className="primary" type="submit">{editing?'保存并复核':'登记档案'}</button></form></section>
 <section className="panel issues"><div className="section-head"><div><span className="kicker">02 / VERIFY</span><h2>异常核对</h2></div><span className="count">{issues.length} 项</span></div>{issues.length===0?<div className="empty"><strong>核对通过</strong><p>当前没有识别到页码或档号问题。</p></div>:<div className="issue-list">{issues.map(i=>{const r=resolutions[i.key];return <article key={i.key}><div><span className={`badge ${r?.status||'pending'}`}>{r?.status==='fixed'?'已修正':r?.status==='kept'?'确认保留':'待核对'}</span><strong>{i.archiveNo}</strong><code>{i.pages} 页</code><p>{i.reason}</p></div><div className="resolution"><select aria-label="问题状态" value={r?.status||''} onChange={e=>{const status=e.target.value as 'fixed'|'kept'|'';setResolutions(p=>{const n={...p};if(status)n[i.key]={status,note:p[i.key]?.note||''};else delete n[i.key];return n})}}><option value="">待核对</option><option value="fixed">已修正</option><option value="kept">确认保留</option></select><input aria-label="处理说明" placeholder="填写核对说明" value={r?.note||''} onChange={e=>setResolutions(p=>({...p,[i.key]:{status:p[i.key]?.status||'kept',note:e.target.value}}))}/></div></article>})}</div>}</section>
 <section className="panel records"><div className="section-head"><div><span className="kicker">03 / ARCHIVES</span><h2>档案清单</h2></div><button className="print" onClick={()=>print()}>打印装盒清单</button></div><div className="filters"><input aria-label="搜索标题或档号" placeholder="搜索标题 / 档号" value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})}/><select aria-label="筛选年度" value={filters.year} onChange={e=>setFilters({...filters,year:e.target.value})}><option value="">全部年度</option>{years.map(y=><option key={y}>{y}</option>)}</select><select aria-label="筛选盒号" value={filters.box} onChange={e=>setFilters({...filters,box:e.target.value})}><option value="">全部盒号</option>{boxes.map(b=><option key={b}>{b}</option>)}</select><select aria-label="筛选问题状态" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value as Filters['status']})}><option value="all">全部状态</option><option value="pending">待核对</option><option value="fixed">已修正</option><option value="kept">确认保留</option></select></div>{visible.length===0?<div className="empty"><strong>{archives.length?'没有匹配结果':'尚未登记档案'}</strong><p>{archives.length?'请调整筛选条件。':'可手动新增、导入 CSV 或载入示例。'}</p></div>:<div className="table-wrap"><table><thead><tr><th>档号 / 标题</th><th>年度</th><th>期限</th><th>盒号</th><th>页码</th><th>申报</th><th>备注</th><th>操作</th></tr></thead><tbody>{visible.map(a=><tr key={a.id}><td><strong>{a.archiveNo}</strong><small>{a.title}</small></td><td>{a.year}</td><td>{a.retention}</td><td><b>{a.boxNo}</b></td><td>{a.startPage}–{a.endPage}</td><td>{a.declaredPages} 页</td><td>{a.note||'—'}</td><td><button onClick={()=>edit(a)}>编辑</button>{isBorrowed(borrows,a.id)?<span className="badge borrowed">借出中</span>:<button onClick={()=>startBorrow(a)}>借阅</button>}<button className="link-danger" onClick={()=>{if(confirm(`删除 ${a.archiveNo}？`)){setArchives(p=>p.filter(x=>x.id!==a.id));setResolutions(p=>Object.fromEntries(Object.entries(p).filter(([k])=>!k.startsWith(`${a.id}:`))))}}}>删除</button></td></tr>)}</tbody></table></div>}</section>
 <section className="panel boxes" id="boxmap"><div className="section-head"><div><span className="kicker">04 / BOX MAP</span><h2>每盒页码区间</h2></div><button className="primary" onClick={openRepage} disabled={boxes.length===0}>连续编页</button></div>
 {repageOpen&&<form className="repage-panel" onSubmit={runPreview}><div className="repage-controls"><label>盒号<select aria-label="连续编页：选择盒号" value={repageBox} onChange={e=>{setRepageBox(e.target.value);setPreview(null)}} required>{boxes.map(b=><option key={b} value={b}>盒 {b}</option>)}</select></label><label>该盒起始页<input aria-label="连续编页：起始页" inputMode="numeric" value={repageStart} onChange={e=>{setRepageStart(e.target.value);setPreview(null)}} placeholder="如 1"/></label><button type="submit">预览重排</button><button type="button" onClick={closeRepage}>取消</button></div>
 {preview&&('error'in preview?<div className="repage-error" role="alert"><strong>无法生成预览</strong><p>{preview.error}</p></div>:<>
 {previewStale&&<div className="repage-error" role="alert"><strong>预览已过期</strong><p>预览后盒 {preview.box} 的档案或其异常处置发生过变化，请重新点击“预览重排”后再确认。</p></div>}
 <div className="repage-summary" role="status"><strong>预览结果（尚未写入）</strong><span>盒 {preview.box} · 共 {preview.rows.length} 件 · 新起点 {preview.startPage} · 将清除 {preview.rows.reduce((n,r)=>n+r.resolutionCount,0)} 条相关旧处置</span></div>
 <div className="table-wrap"><table className="repage-table"><thead><tr><th>档号 / 标题</th><th>申报页数</th><th>原区间</th><th>新区间</th><th>受影响处置</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.archive.id}><td><strong>{r.archive.archiveNo}</strong><small>{r.archive.title}</small></td><td>{r.archive.declaredPages} 页</td><td className="old-range">{r.oldStart}—{r.oldEnd}</td><td className="new-range">{r.newStart}—{r.newEnd}</td><td>{r.resolutionCount?`${r.resolutionCount} 条`:'—'}</td></tr>)}</tbody></table></div>
 <div className="repage-actions"><button type="button" className="primary" onClick={confirmRepage} disabled={previewStale} title={previewStale?'请先重新预览':'确认写入'}>确认写入</button><button type="button" onClick={closeRepage}>取消（不落盘）</button></div></>)}
 </form>}
 {grouped.length===0?<div className="empty"><p>暂无装盒数据。</p></div>:<div className="box-grid">{grouped.map(g=><article key={g.box}><header><strong>盒 {g.box}</strong><span>{g.items.length} 件</span></header>{g.items.map(a=><div key={a.id}><code>{a.startPage}—{a.endPage}</code><span>{a.archiveNo}</span><small>{a.title}</small></div>)}<InventoryPanel box={g.box} session={latestByBox.get(g.box)} onStart={()=>startInventory(g.box)} onSession={saveSession}/></article>)}</div>}</section>
 <BorrowPanel records={borrows} target={borrowTarget} error={borrowError} onConfirm={confirmBorrow} onCancel={cancelBorrow} onReturn={doReturn}/>
 </main><footer>ARCHIVE BOX PAGE AUDIT · 本地数据工作台</footer></>}
